"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_recipe_recipes_post(self):
        """Test case for create_recipe_recipes_post

        Create Recipe  # noqa: E501
        """
        pass

    def test_get_recipe_recipes_recipe_id_get(self):
        """Test case for get_recipe_recipes_recipe_id_get

        Get Recipe  # noqa: E501
        """
        pass

    def test_get_recipes_recipes_get(self):
        """Test case for get_recipes_recipes_get

        Get Recipes  # noqa: E501
        """
        pass

    def test_update_recipe_recipes_recipe_id_put(self):
        """Test case for update_recipe_recipes_recipe_id_put

        Update Recipe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
