"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recipe_dificulty import RecipeDificulty
from openapi_client.model.recipe_duration import RecipeDuration
from openapi_client.model.recipe_ingredient import RecipeIngredient
from openapi_client.model.recipe_instruction import RecipeInstruction
from openapi_client.model.recipe_serves import RecipeServes
from openapi_client.model.recipe_tool import RecipeTool
globals()['RecipeDificulty'] = RecipeDificulty
globals()['RecipeDuration'] = RecipeDuration
globals()['RecipeIngredient'] = RecipeIngredient
globals()['RecipeInstruction'] = RecipeInstruction
globals()['RecipeServes'] = RecipeServes
globals()['RecipeTool'] = RecipeTool
from openapi_client.model.recipe import Recipe


class TestRecipe(unittest.TestCase):
    """Recipe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecipe(self):
        """Test Recipe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Recipe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
