"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ingredient_quantity_unit import IngredientQuantityUnit
globals()['IngredientQuantityUnit'] = IngredientQuantityUnit
from openapi_client.model.ingredient_quantity import IngredientQuantity


class TestIngredientQuantity(unittest.TestCase):
    """IngredientQuantity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIngredientQuantity(self):
        """Test IngredientQuantity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IngredientQuantity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
