@startuml request-response

title Request-Response Diagram

actor Customer

Customer -> Auth: authenticate
Auth --> Customer: token
Customer -> ReverseProxy: GET /recipes/{recipe_id}
ReverseProxy -> Auth: validate token
Auth --> ReverseProxy: token is valid
ReverseProxy -> RequestHandler: invoke
database Storage
RequestHandler -> Storage: read recipe
Storage --> RequestHandler: recipe
RequestHandler --> ReverseProxy: recipe
ReverseProxy --> Customer: recipe

@enduml