@startuml request-response

title Request-Response Diagram

actor Customer

Customer -> Auth: authenticate
Auth --> Customer: token
Customer -> ReverseProxy: create, read, update recipe
ReverseProxy -> Auth: validate token
Auth --> ReverseProxy: token is valid
ReverseProxy -> RequestHandler: invoke
database Storage
RequestHandler -> Storage: read, write recipe
Storage --> RequestHandler: ok
RequestHandler --> ReverseProxy: ok
ReverseProxy --> Customer: ok

@enduml